package epsilon.syntax;

public enum Kind {

    UnknownToken,
    EndToken,
    LiteralToken,
    WhitespaceToken,
    Number,
    ReturnKw,
    FuncKw,
    Arrow,
    LetKw,
    Assign,
    CloseBracket,
    OpenBracket,
    Semicolon,
    Colon,
    OpenParenthesis,
    CloseParenthesis,
    DoubleQuoteSymbol,
    ReturnLineSymbol,
    QuoteSymbol,
    Minus,
    Plus,
    Slash,
    Star,
    CommaSymbol,
    Dot,
    Equal,
    LessEqual,
    GreaterEqual,
    NotEqual,
    Not,
    String,
    ParenthesizedExpression,
    EmptyExpression,
    BinaryExpression,
    UnknownExpression,
    NullKw,
    IfKw,
    ElseKw,
    ThisKw,
    ForKw,
    ClassKw,
    WhileKw,
    Less,
    Greater,
    Identifier,
    MethodSymbol,
    TrueKw,
    FalseKw,
    MutKw,
    BinaryAnd,
    LogicalAnd,
    BinaryOr,
    LogicalOr,
    BreakKw,
    NamespaceKw,
    StructKw, Hash,

}
