package epsilonc;

public enum Kind {

    UnknownToken,
    EndToken,
    LiteralToken,
    WhitespaceToken,
    Number,
    ReturnSymbol,
    FuncSymbol,
    ArrowSymbol,
    LetSymbol,
    Assign,
    CloseBracket,
    OpenBracket,
    Semicolon,
    Colon,
    OpenParenthesis,
    CloseParenthesis,
    DoubleQuoteSymbol,
    ReturnLineSymbol,
    QuoteSymbol,
    Minus,
    Plus,
    Slash,
    Star,
    CommaSymbol,
    Dot,
    Equal,
    LessEqual,
    GreaterEqual,
    NotEqual,
    Not,
    String,
    ParenthesizedExpression,
    EmptyExpression,
    BinaryExpression,
    UnknownExpression,
    NullSymbol,
    IfSymbol,
    ElseSymbol,
    ThisSymbol,
    ForSymbol,
    ClassSymbol,
    WhileSymbol,
    Less,
    Greater,
    Identifier,
    MethodSymbol,
    True,
    False,
    MutSymbol,
    BinaryAnd,
    LogicalAnd,
    BinaryOr,
    LogicalOr,
    BreakSymbol, NamespaceSymbol,

}
